OnlineShop/Controllers/AboutController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class AboutController : Controller
    {
        // GET: About
        public ActionResult Index()
        {
            return View();
        }
    }
}

OnlineShop/Controllers/CategoryController.cs
using OnlineShop.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class CategoryController : Controller
    {
        // GET: Category
        ShopEntities1 objModel = new ShopEntities1();
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ProductsCategory(int Id)
        {
            var ListProduct = objModel.Product.Where(n => n.CategoryId == Id).ToList();

            return View(ListProduct);
        }
    }
}

OnlineShop/Controllers/ContactController.cs
using OnlineShop.Context;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class ContactController : Controller
    {
        ShopEntities1 db = new ShopEntities1();
        // GET: Contact
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Index(string Name, string Email, string CompanyName, string Subject)
        {
            Response response = new Response();
            response.Name = Name;
            response.Email = Email;
            response.CompanyName = CompanyName;
            response.Subject = Subject;
            db.Response.Add(response);
            db.SaveChanges();
            ViewBag.camon = "Cảm ơn bạn đã gửi phản hồi";
            return RedirectToAction("Index","Home");
        }
    }
}

OnlineShop/Controllers/HomeController.cs
using OnlineShop.Context;
using OnlineShop.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class HomeController : Controller
    {
        ShopEntities1 objModel =  new ShopEntities1();
        
        public ActionResult AllProduct(string SearchString)
        {
            var lstProduct = objModel.Product.ToList();
            if (!String.IsNullOrEmpty(SearchString))
            {
                lstProduct = objModel.Product.Where(n => n.Name.Contains(SearchString)).ToList();
            }
            else
            {
                lstProduct = objModel.Product.ToList();
            }
            var lstCategory = objModel.Category.ToList(); 
            Product_Category objProduct_Category = new Product_Category();
            objProduct_Category.ListCategory = lstCategory;
            objProduct_Category.ListProduct = lstProduct;
            return View(objProduct_Category);
        }
        public ActionResult Index()
        {
            var lstCategory = objModel.Category.ToList();
            var lstProduct = objModel.Product.OrderByDescending(x => x.Id).Take(4).ToList();
            Product_Category objProduct_Category = new Product_Category();
            objProduct_Category.ListCategory = lstCategory;
            objProduct_Category.ListProduct = lstProduct;
            return View(objProduct_Category);
        }
        //GET: Register
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }
        //POST: Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Register(Users _user)
        {
            if (ModelState.IsValid)
            {
                var check = objModel.Users.FirstOrDefault(n => n.Email == _user.Email);
                if (check == null)
                {
                    _user.Password = GetMD5(_user.Password);
                    objModel.Configuration.ValidateOnSaveEnabled = false;
                    objModel.Users.Add(_user);
                    objModel.SaveChanges();
                    return RedirectToAction("Login");
                }
                else
                {
                    ViewBag.error = "Email đã tồn tại";
                    return View();
                }
            }
            return View();
        }
        public static string GetMD5(string str)
        {
            MD5 md5 = new MD5CryptoServiceProvider();
            byte[] formData = Encoding.UTF8.GetBytes(str);
            byte[] targetData = md5.ComputeHash(formData);
            string byte2String = null;
            for(int i = 0; i < targetData.Length; i++)
            {
                byte2String += targetData[i].ToString("x2");
            }
            return byte2String;
        }
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(string email,string password)
        {
            if (ModelState.IsValid)
            {
                var f_password = GetMD5(password);
                var data = objModel.Users.Where(n => n.Email.Equals(email) && n.Password == f_password);
                if (data.Count() > 0)
                {
                    Session["Fullname"] = data.FirstOrDefault().FirstName + " " + data.FirstOrDefault().LastName;
                    Session["Email"] = data.FirstOrDefault().Email;
                    Session["idUser"] = Convert.ToInt32(data.FirstOrDefault().idUser);
                    if (Session["Email"].ToString() == "admin@gmail.com")
                    {
                        Session["Admin"] = 1;
                    }
                    else
                    {
                        Session["Admin"] = null;
                    }
                    
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.error = "Sai tên đăng nhập hoặc mật khẩu";
                    return RedirectToAction("Login");
                }
                
            }
            return View();
        }
        
        [HttpGet]
        public ActionResult ChangePassword(int Id)
        {
            Session["idUser"] = Id;
            var objUser = objModel.Users.FirstOrDefault(n => n.idUser == Id);
            return View(objUser);
        }
        [HttpPost]
        public ActionResult ChangePassword(int Id, FormCollection f)
        {
        
            Session["idUser"] = Id;
            var objUser = objModel.Users.FirstOrDefault(n => n.idUser == Id);
            if (objUser.Password == GetMD5(f["oldPassword"]))
            {
                var newpass = f["newPassword"];
                var confirmpass = f["confirmpass"];
                if (newpass == confirmpass)
                {
                    objUser.Password = GetMD5(newpass);
                    objModel.SaveChanges();
                    ViewBag.error = "Đổi mật khẩu thành công!";
                }
                else
                {
                    ViewBag.error2 = "Không khớp với mật khẩu bạn vừa nhập!";
                }  
            }
            else
            {
                ViewBag.error1 = "Bạn nhập sai mật khẩu hiện tại!";
            }

            return RedirectToAction("Login");
        }
         
        [HttpGet]
        public ActionResult Infor(int Id)
        {
            Session["idUser"] = Id;
            var objUser = objModel.Users.FirstOrDefault(n => n.idUser == Id);
            return View(objUser);
        }
        [HttpPost]
        public ActionResult Infor(int Id, FormCollection f)
        {
            Session["idUser"] = Id;
            var objUser = objModel.Users.FirstOrDefault(n => n.idUser == Id);
            var firstN = f["firstName"];
            var lastN = f["lastName"];
            objUser.FirstName = firstN;
            objUser.LastName = lastN;
            objModel.SaveChanges();
            ViewBag.error = "Đổi thông tin thành công!";
            return View(objUser);

        } 
        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Login");
        }
    }
}

OnlineShop/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

OnlineShop/Views/Home/AllProduct.cshtml
@model OnlineShop.Models.Product_Category
@{
    ViewBag.Title = "Product";
}
<div class="header_bottom">
    <div class="menu">
        <ul>
            <li><a href="~/Home/Index">Trang chủ</a></li>
            <li><a href="~/About/Index">Thông tin</a></li>
            <li><a href="~/News/Index">Tin tức</a></li>
            <li><a href="~/Contact/Index">Liên hệ</a></li>
            <li class="active"><a href="~/Home/AllProduct">Sản phẩm</a></li>

        </ul>
    </div>
    <div class="search_box">
        @using (Html.BeginForm())
        {
            <form>
                @Html.TextBox("SearchString")<input type="submit" value="" />
            </form>
        }
    </div>
    <div class="clear"></div>
</div>
<div class="main">
    <div class="content">

        <div class="section group">
            @foreach (var item in Model.ListProduct)
            {
                <div style="margin:10px 10px 0 0 ; width:250px; height:350px" class="grid_1_of_4 images_1_of_4">
                    <a href="~/Product/Index/@item.Id"><img width="250" height="250" src="~/Content/images/@item.Avatar" alt=""></a>
                    <h2 style="height:40px; " >
                        <span style="vertical-align: middle">@Html.ActionLink(item.Name, "Index", "Product", new { Id = item.Id }, null)</span>
                    </h2>
                    <div class="price-details">
                        <div class="price-number">
                            @{
                                string tien = "";
                                int price = (int)item.Price;
                                tien = price.ToString("#,##0");
                            }
                            <p><span class="rupees">@tien đ</span></p>
                        </div>
                        @*<div class="add-cart">
                                <h4><a href="preview.html">Add to Cart</a></h4>
                            </div>*@
                        <div class="clear"></div>
                    </div>

                </div>
            }

        </div>

    </div>
</div>

OnlineShop/Views/Home/ChangePassword.cshtml
@{
    ViewBag.Title = "ChangePassword";
}


<html>
<head>
    
</head>


<body>
    <div class="main">
    <div class="content">
        <div class="section group">
            <div class="col span_2_of_3">
                <div class="contact-form">
                    <h2>Thay đổi mật khẩu</h2>
                    @using (Html.BeginForm())
                    {
                        <div>
                            <span><label>Mật khẩu cũ</label></span>
                            <span><input required type="password" name="oldPassword" class="form-control" placeholder="Nhập mật khẩu cũ"></span>
                            <span>@ViewBag.error1</span>
                        </div>
                        <div>
                            <span><label>Mật khẩu mới</label></span>
                            <span><input required type="password" name="newPassword" class="form-control" placeholder="Nhập mật khẩu mới"></span>
                            <span></span>
                        </div>
                        <div>
                            <span><label>Xác nhận mật khẩu mới</label></span>
                            <span><input required type="password" name="confirmpass" class="form-control" placeholder="Nhập lại mật khẩu"></span>
                            <span>@ViewBag.error2</span>
                        </div>
                        <div>
                            <span><input type="submit" value="Lưu" class="btn"></span>
                            <span><a href="~/Home/Index"><input type="button" value="Trở lại trang chủ" class="btn" /></a></span>
                        </div>
                        <span style="color:red ;"><b>@ViewBag.error</b></span>
                    }


                </div>
            </div>
        </div>
    </div>
</div>
                    </body>
</html>

OnlineShop/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

OnlineShop/Views/Home/Index.cshtml
@model OnlineShop.Models.Product_Category
@{
    ViewBag.Title = "Home Page";
}
@*@Html.Partial("_Slide")*@
<style>
    #slider {
        height: 40% !important;
    }
</style>
<div class="header_bottom">
    <div class="menu">
        <ul>
            <li class="active">
                <a href="~/Home/Index">Trang chủ</a>
            </li>
            <li><a href="~/About/Index">Thông tin</a></li>
            <li><a href="~/News/Index">Tin tức</a></li>
            <li><a href="~/Contact/Index">Liên hệ</a></li>
            <li><a href="~/Home/AllProduct">Sản phẩm</a></li>

        </ul>
    </div>
   
    <div class="clear"></div>
</div>
<div class="header_slide">
    <div class="header_bottom_left">
        <div class="categories">
            <h3>Danh mục sản phẩm</h3>
            <ul>

                @foreach (var item in Model.ListCategory)
                {
                    <li>

                        @Html.ActionLink(item.Name, "ProductsCategory", "Category", new { @Id = item.Id }, null)

                    </li>
                }
            </ul>
        </div>
    </div>
    <div class="header_bottom_right">
        <div class="slider">
            <div id="slider">
                <div id="mover">
                    <div id="slide-1" class="slide">
                        <div style="width:48%" class="slider-img">
                            <a href=""><img src="~/Content/images/home.png" alt="learn more" /></a>
                        </div>
                        <div style="padding:20px" class="slider-text">
                            <h1 style="font-size:2.1em; margin:15px 0 15px 0 ">ĐIỆN MÁY TRƯỜNG HOA<br></h1>
                            <h2 style="font-size:1.8em">UY TÍN - CHẤT LƯỢNG</h2>
                            <div class="features_list">
                                <h4>Tất cả cho khách hàng – khách hàng cho tất cả</h4>
                            </div>
                            
                        </div>
                        <div class="clear"></div>
                    </div>
                    @*<div class="slide">
                        <div class="slider-text">
                            <h1>Clearance<br><span>SALE</span></h1>
                            <h2>UPTo 40% OFF</h2>
                            <div class="features_list">
                                <h4>Get to Know More About Our Memorable Services</h4>
                            </div>
                            <a href="preview.html" class="button">Shop Now</a>
                        </div>
                        <div class="slider-img">
                            <a href="preview.html"><img src="~/Content/images/slide-3-image.jpg" alt="learn more" /></a>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="slide">
                        <div class="slider-img">
                            <a href="preview.html"><img src="~/Content/images/slide-2-image.jpg" alt="learn more" /></a>
                        </div>
                        <div class="slider-text">
                            <h1>Clearance<br><span>SALE</span></h1>
                            <h2>UPTo 10% OFF</h2>
                            <div class="features_list">
                                <h4>Get to Know More About Our Memorable Services Lorem Ipsum is simply dummy text</h4>
                            </div>
                            <a href="preview.html" class="button">Shop Now</a>
                        </div>
                        <div class="clear"></div>
                    </div>*@
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="clear"></div>
</div>

<div class="main">
    <div class="content">
        <div class="content_top">
            <div class="heading">
                <h3>SẢN PHẨM MỚI</h3>
            </div>
            <div class="see">
                <p><a href="~/Home/AllProduct">Tất cả sản phẩm</a></p>
            </div>
            <div class="clear"></div>
        </div>
        <div class="section group">
            @foreach (var item in Model.ListProduct)
            {
                <div class="grid_1_of_4 images_1_of_4">
                    <a href="~/Product/Index/@item.Id"><img width="250" height="250" src="~/Content/images/@item.Avatar" alt=""></a>
                    <h2>
                    @Html.ActionLink(item.Name, "Index","Product",new {Id = item.Id },null) 
                    </h2>
                    <div class="price-details">
                        <div class="price-number">
                            @{
                                string tien = "";
                                int price = (int)item.Price;
                                tien = price.ToString("#,##0");
                            }
                            <p><span class="rupees">@tien đ</span></p>
                        </div>
                        @*<div class="add-cart">
                            <h4><a href="preview.html">Add to Cart</a></h4>
                        </div>*@
                        <div class="clear"></div>
                    </div>

                </div>
            }

        </div>

    </div>
</div>

OnlineShop/Views/Home/Infor.cshtml
@model OnlineShop.Context.Users
@{
    ViewBag.Title = "Infor";
}


<div class="main">
    <div class="content">
        <div class="section group">
            <div class="col span_2_of_3">
                <div class="contact-form">
                    <h2>Thông tin người dùng</h2>
                    @using (Html.BeginForm())
                    {
                        <div>
                            <span><label>Họ</label></span>
                            <span><input required type="text" name="firstName" class="form-control" placeholder="@Model.FirstName"></span>
                        </div>
                        <div>
                            <span><label>Tên</label></span>
                            <span><input required type="text" name="lastName" class="form-control" placeholder="@Model.LastName"></span>
                        </div>
                        <div>
                            <span><label>Tên đăng nhập (Email)</label></span>
                            <span><input required type="text" name="Email" class="form-control" placeholder="@Model.Email" readonly></span>
                        </div>
                        <div>
                            <span><input type="submit" value="Lưu" class="btn"></span>
                            <span><a href="~/Home/Index"><input type="button" value="Trở lại trang chủ" class="btn" /></a></span>
                        </div>
                        <span style="color:red"><b>@ViewBag.error</b></span>
                    }

                </div>
            </div>
        </div>
    </div>
</div>

OnlineShop/Views/Home/Login.cshtml
@model OnlineShop.Context.Users
@{
    ViewBag.Title = "Login";
}
<style>
    #login {
        background-color: limegreen;
        border: none;
        color: black;
        width: 100%;
        padding: 10px 0;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
    }
    #Password {
        padding: 8px !important;
        margin: unset !important;
        width: 40% !important;
    }
</style>
<div class="main">
    <div class="content">
        <div class="section group">
            <div class="col span_2_of_3">
                <h2 id="login">Đăng nhập</h2>
                <hr />
                <div  class="contact-form">


                    @using (Html.BeginForm("Login", "Home", FormMethod.Post))
                    {
                        @Html.AntiForgeryToken()
                    <div align="center">
                        <div class="form-group" style="width: 41% !important;">
                            @*@Html.LabelFor(m => m.Email)*@
                            <div class="col-md-10">
                                @Html.TextBoxFor(m => m.Email, "", new { @class = "form-control", @placeholder = "Email" })
                            </div>
                        </div>
                        <div class="form-group">
                            @*@Html.LabelFor(m => m.Password)<br />*@
                            <div class="col-md-10">
                                @Html.PasswordFor(m => m.Password, new { @class = "form-control", @placeholder = "Mật khẩu" })
                            </div>
                        </div>
                        <div style="color:red">@ViewBag.error</div>
                        <div>
                            @ViewBag.error
                        </div>
                        <div class="form-group">
                            <input align="center" type="submit" name="submit" class="btn btn-primary" value="Đăng nhập" style="right: 230px; " />
                        </div>
                    </div>
                    }
                </div>
            </div>
        </div>            
    </div>   
</div>

OnlineShop/Views/Home/Register.cshtml
@model OnlineShop.Context.Users

@{
    ViewBag.Title = "Register";
}
<style>
    #regis {
        background-color: limegreen;
        border: none;
        color: black;
        width: 100%;
        padding: 10px 0;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 16px;
        margin: 4px 2px;
    }
    #FirstName{
        width:40%;
    }
    #LastName{
        width:40%;
    }
    #Email{
        width:40%;
    }
    #Password{
        width:40%;
    }
</style>
<div class="main">
    <div class="content">
        <div class="section group">
            <div class="col span_2_of_3">
                <div class="contact-form">
                    <h2 id="regis">Đăng kí</h2>
                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div align="center" class="form-horizontal">
                            
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="form-group">
                                @*@Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" ,@placeholder ="Tên"} })
                                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @*@Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control", @placeholder = "Họ" } })
                                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @*@Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control", @placeholder = "Email" } })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                @*@Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })*@
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", @placeholder = "Mật khẩu" } })
                                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Đăng kí" class="btn btn-default" style="right: 230px;" />
                                </div>
                                <div style="color:red ">@ViewBag.error</div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>




<div>
    @Html.ActionLink("Trở lại trang chủ", "Index")
</div>