OnlineShop/Areas/Admin/Controllers/CategoryAdminController.cs
using OnlineShop.Context;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class CategoryAdminController : Controller
    {
        ShopEntities1 dbObj = new ShopEntities1();
        // GET: Admin/Category
        public ActionResult Index()
        {
            if (Session["Admin"] != null)
            {
                var lstCategory = dbObj.Category.ToList();
                return View(lstCategory);
            }
            else
            {
                return Redirect("https://localhost:44353/Home/Login");
            }
            
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Category objCategory)
        {
            try
            {
                if (objCategory.ImageUpload != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(objCategory.ImageUpload.FileName);
                    string extention = Path.GetExtension(objCategory.ImageUpload.FileName);
                    fileName = fileName + extention;
                    objCategory.Avatar = fileName;
                    objCategory.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/"), fileName));
                }
                dbObj.Category.Add(objCategory);
                dbObj.SaveChanges();
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                return RedirectToAction("Index");
            }
            
        }
        [HttpGet]
        public ActionResult Details(int Id)
        {
            var objCategory = dbObj.Category.Where(n => n.Id == Id).FirstOrDefault();
            return View(objCategory);
        }
        [HttpGet]
        public ActionResult Delete(int Id)
        {
            var objCategory = dbObj.Category.Where(n => n.Id == Id).FirstOrDefault();
            return View(objCategory);
        }
        [HttpPost]
        public ActionResult Delete(Category objCate)
        {
            var objCategory = dbObj.Category.Where(n => n.Id == objCate.Id).FirstOrDefault();
            dbObj.Category.Remove(objCategory);
            dbObj.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Edit(int Id)
        {
            var objCategory = dbObj.Category.Where(n => n.Id == Id).FirstOrDefault();
            return View(objCategory);
        }
        [HttpPost]
        public ActionResult Edit(Category objCategory, FormCollection form)
        {
            if (objCategory.ImageUpload != null)
            {
                if (objCategory.Avatar != null)
                {
                    string fileName = Path.GetFileNameWithoutExtension(objCategory.ImageUpload.FileName);
                    string extention = Path.GetExtension(objCategory.ImageUpload.FileName);
                    fileName = fileName + extention;
                    objCategory.Avatar = fileName;
                    objCategory.ImageUpload.SaveAs(Path.Combine(Server.MapPath("~/Content/images/"), fileName));
                }
                else
                {
                    objCategory.Avatar = form["oldimage"];
                }
                dbObj.Entry(objCategory).State = EntityState.Modified;
                dbObj.SaveChanges();
            }
            return RedirectToAction("Index");
            
        }
    }
}

OnlineShop/Areas/Admin/Views/CategoryAdmin/Create.cshtml
@model OnlineShop.Context.Category

@{
    ViewBag.Title = "Create";
    Layout = "~/Areas/Admin/Views/SharedAdmin/_Layout.cshtml";
}


@using (Html.BeginForm("Create", "CategoryAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="modal-header bg-success">
        <h3 class="modal-title">Thêm danh mục <span style="color:red">@ViewBag.Message</span></h3>
    </div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="modal-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-6">

                <div class="form-group row">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "col-sm-4 col-form-label input-required" })
                    <div class="col-sm-8">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>
                

            </div>
            <!--./col-->
            <!-- Col -->
            <div class="col-md-6">
                <div class="form-group row">
                    @Html.LabelFor(model => model.Avatar, htmlAttributes: new { @class = "col-sm-4 col-form-label input-required" })
                    <div class="col-sm-8">
                        <input type="file" name="ImageUpload" />
                    </div>
                </div>
                
            </div>
            <!--./col-->
        </div>
        <!--./row-->
    </div>
    <div>
    </div>
    <div class="modal-footer">
        @Html.ActionLink("Trở lại danh sách", "Index")
        <input type="submit" value="Thêm" class="btn btn-outline-primary quickSubmit" />

    </div>
    

}

OnlineShop/Areas/Admin/Views/CategoryAdmin/Delete.cshtml
@model OnlineShop.Context.Category

@{
    ViewBag.Title = "Delete";
    Layout = "~/Areas/Admin/Views/SharedAdmin/_Layout.cshtml";
}

<div class="modal-header bg-success">
    <h3 class="modal-title" id="planCreateModalTitle">Xóa danh mục @Model.Name</h3>
</div>
<div asp-validation-summary="ModelOnly" class="text-danger"></div>
<input type="hidden" asp-for="Id" />
<div class="modal-body">

    <div class="row">
        <div class="col-md-6">

            
            <div class="form-group row">
                <label class="col-sm-4 col-form-label input-required">Ảnh</label>
                <div class="col-sm-8">
                    @{
                        string ImagePath = "~/Content/images/" + Model.Avatar;
                    }
                    <img src="@Url.Content(ImagePath)" width="300" class="img-thumbnail" />
                </div>
            </div>

        </div>
        <!--./col-->
        <!-- Col -->
        <div class="col-md-6">
            <div class="form-group row">
                <label class="col-sm-4 col-form-label input-required">Tên danh mục</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" placeholder="@Model.Name" disabled />
                </div>
            </div>
        </div>
        <!--./col-->
    </div>
    <!--./row-->
</div>

@using (Html.BeginForm("Delete", "CategoryAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="modal-footer">
    <input type="submit" value="Xóa" class="btn btn-danger" />
    @Html.ActionLink("Trở lại danh sách", "Index")
</div>
}

OnlineShop/Areas/Admin/Views/CategoryAdmin/Details.cshtml
@model OnlineShop.Context.Category

@{
    ViewBag.Title = "Details";
    Layout = "~/Areas/Admin/Views/SharedAdmin/_Layout.cshtml";
}



<form class="modal-content validateForm bv-form onUpdateInputState" form asp-action="Details">
    <div class="modal-header bg-success">
        <h3 class="modal-title" id="planCreateModalTitle">Thông tin danh mục @Model.Name</h3>
    </div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="modal-body">

        <div class="row">
            <div class="col-md-6">

               
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label input-required">Ảnh</label>
                    <div class="col-sm-8">
                        @{
                            string ImagePath = "~/Content/images/" + Model.Avatar;
                        }
                        <img src="@Url.Content(ImagePath)" width="300" class="img-thumbnail" />
                    </div>
                </div>

            </div>
            <!--./col-->
            <!-- Col -->
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label input-required">Tên</label>
                    <div class="col-sm-8">
                        @Html.DisplayFor(model => model.Name)
                    </div>
                </div>
                
            </div>
            <!--./col-->
        </div>
        <!--./row-->
    </div>
    <div>

    </div>
    <div class="modal-footer">

        @Html.ActionLink("Trở lại danh sách", "Index")
        <a class="btn btn-outline-info quickUpdate" href="~/Admin/CategoryAdmin/Edit/@Model.Id">Sửa</a>

    </div>
</form>

OnlineShop/Areas/Admin/Views/CategoryAdmin/Edit.cshtml
@model OnlineShop.Context.Category

@{
    ViewBag.Title = "Edit";
    Layout = "~/Areas/Admin/Views/SharedAdmin/_Layout.cshtml";
}

<h2>Sửa danh mục</h2>

@using (Html.BeginForm("Edit", "CategoryAdmin", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="modal-header bg-success">
        <h3 class="modal-title" id="planCreateModalTitle">Sửa danh mục @Model.Name</h3>
    </div>
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="Id" />
    <div class="modal-body">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="row">
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label input-required">Ảnh</label>
                    <div class="col-sm-8">
                        @Html.TextBoxFor(model => model.Avatar, null, new { type = "file", @class = "form-control" })
                        <img src="~/Content/images/@Model.Avatar" width="200" class="img-thumbnail" />
                        @Html.Hidden("oldimage", @Model.Avatar)
                        @Html.ValidationMessageFor(model => model.Avatar, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>
            <!--./col-->
            <!-- Col -->
            <div class="col-md-6">
                <div class="form-group row">
                    <label class="col-sm-4 col-form-label input-required">Tên danh mục</label>
                    <div class="col-sm-8">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div> 
            </div>
            <!--./col-->
        </div>
        <!--./row-->
    </div>
    <div>

    </div>
    <div class="modal-footer">
        @Html.ActionLink("Trở lại danh sách", "Index")
        <input type="submit" value="Lưu" class="btn btn-outline-primary quickSubmit" />

    </div>
}

OnlineShop/Areas/Admin/Views/CategoryAdmin/Index.cshtml
@model IEnumerable<OnlineShop.Context.Category>

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Danh sách danh mục </h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="table-control col-sm-12 col-md-6">
                        
                    </div>
                    <div class="table-control col-sm-12 col-md-6 text-right">
                        <a class="btn btn-success quickUpdate" href="~/Admin/CategoryAdmin/Create">
                            <i class="fas fa-fw fa-plus"></i><span>Thêm mới</span>
                        </a>
                        
                    </div>
                </div>

                <div id="dataTables_wrapper" class="dataTables_wrapper">
                    <table class="table">
                        <thead>
                            <tr>

                                <th>
                                    Tên
                                </th>
                                <th>
                                    
                                </th>
                                <th>
                                    Ảnh
                                </th>
                                <th>
                                    
                                </th>
                                <th>
                                    Thao tác
                                </th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>

                                    <td>
                                        @Html.DisplayFor(modelItem => item.Name)
                                    </td>
                                    <td>
                                        
                                    </td>
                                    <td>
                                        @{
                                            string ImagePath = "~/Content/images/" + item.Avatar;
                                        }
                                        <img src="@Url.Content(ImagePath)" width="100" class="img-thumbnail" />
                                    </td>
                                    <td>
                                        
                                    </td>

                                    <td>
                                        <a title="Xem chi tiết" class="btn btn-sm btn-outline-secondary btn-hover-success quickUpdate" href="~/Admin/CategoryAdmin/Details/@item.Id">
                                            <i class="fas fa-fw fa-info"></i>
                                        </a>
                                        <a title="Sửa" class="btn btn-sm btn-outline-secondary btn-hover-info quickUpdate" href="~/Admin/CategoryAdmin/Edit/@item.Id">
                                            <i class="fas fa-fw fa-edit"></i>
                                        </a>
                                        <a title="Xóa" class="btn btn-sm btn-outline-secondary btn-hover-danger quickDelete" href="~/Admin/CategoryAdmin/Delete/@item.Id">
                                            <i class="fas fa-fw fa-trash-alt"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                   
                </div>
            </div>
        </div>
    </div>
</div>