OnlineShop/Controllers/CartController.cs
using Newtonsoft.Json.Linq;
using OnlineShop.Context;
using OnlineShop.Models;
using OnlineShop.Payment;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OnlineShop.Controllers
{
    public class CartController : Controller
    {
        // GET: Cart
        ShopEntities1 db = new ShopEntities1();
        public ActionResult Index()
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else {
                return View((List<Cart>)Session["cart"]);
            }
            
        }
        
        public ActionResult AddToCart(int id, int quantity)
        {
            if(Session["cart"] == null)
            {
                List<Cart> cart = new List<Cart>();
                cart.Add(new Cart { Product = db.Product.Find(id), Quantity = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<Cart> cart = (List<Cart>)Session["cart"];
                //Kiểm tra xem sản phẩm đã tồn tại trong giỏ hàng chưa
                int index = isExist(id);
                if(index != -1)
                {
                    //Nếu sản phẩm tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].Quantity += quantity;
                }
                else
                {
                    //Nếu không tồn tại thì thêm vào giỏ hàng
                    cart.Add(new Cart { Product = db.Product.Find(id), Quantity = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

        private int isExist(int id)
        {
            List<Cart> cart = (List<Cart>)Session["cart"];
            for(int i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.Id.Equals(id))
                {
                    return i;
                }
            }
            return -1;
        }
        public ActionResult Remove(int Id)
        {
            List<Cart> li = (List<Cart>)Session["cart"];
            li.RemoveAll(n => n.Product.Id == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

        #region PaymentMoMo
        [HttpGet]
        public ActionResult Payment()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Payment(string Name, string Phone, string Address)
        {
            int tong = 0;
            if (Session["idUser"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                var lstCart = (List<Cart>)Session["cart"];
                Order objOrder = new Order();
                objOrder.Name = Name;
                objOrder.Phone = Phone;
                objOrder.Adress = Address;
                objOrder.UserId = int.Parse(Session["idUser"].ToString());
                objOrder.CreateOnUtc = DateTime.Now;
                objOrder.Status = 1;
                db.Order.Add(objOrder);
                db.SaveChanges();
                int intOrderId = objOrder.Id;
                List<OrderDetail> lstOrderDetail = new List<OrderDetail>();
                foreach (var item in lstCart)
                {
                    OrderDetail objOrderDetail = new OrderDetail();
                    objOrderDetail.Quantity = item.Quantity;
                    objOrderDetail.ProductId = item.Product.Id;
                    objOrderDetail.ProductName = item.Product.Name;
                    objOrderDetail.Price = item.Product.Price;
                    int gia = (int)objOrderDetail.Price;
                    int soluong = (int)objOrderDetail.Quantity;
                    int tien = gia * soluong;
                    tong = tong + tien;
                    objOrderDetail.OrderId = intOrderId;
                    lstOrderDetail.Add(objOrderDetail);
                }
                db.OrderDetail.AddRange(lstOrderDetail);
                db.SaveChanges();
                
                string endpoint = "https://test-payment.momo.vn/gw_payment/transactionProcessor";
                string partnerCode = "MOMOOJOI20210710";
                string accessKey = "iPXneGmrJH0G8FOP";
                string serectkey = "sFcbSGRSJjwGxwhhcEktCHWYUuTuPNDB";
                string orderInfo = "Thanh toán tiền hàng";
                string returnUrl = "https://localhost:44353/Cart/Success";
                string notifyurl = "https://4c8d-2001-ee0-5045-50-58c1-b2ec-3123-740d.ap.ngrok.io/Home/SavePayment"; //lưu ý: notifyurl không được sử dụng localhost, có thể sử dụng ngrok để public localhost trong quá trình test

                string amount = Convert.ToString(tong);
                string orderid = DateTime.Now.Ticks.ToString(); //mã đơn hàng
                string requestId = DateTime.Now.Ticks.ToString();
                string extraData = "";

                //Before sign HMAC SHA256 signature
                string rawHash = "partnerCode=" +
                    partnerCode + "&accessKey=" +
                    accessKey + "&requestId=" +
                    requestId + "&amount=" +
                    amount + "&orderId=" +
                    orderid + "&orderInfo=" +
                    orderInfo + "&returnUrl=" +
                    returnUrl + "&notifyUrl=" +
                    notifyurl + "&extraData=" +
                    extraData;

                MoMoSecurity crypto = new MoMoSecurity();
                //sign signature SHA256
                string signature = crypto.signSHA256(rawHash, serectkey);

                //build body json request
                JObject message = new JObject
            {
                { "partnerCode", partnerCode },
                { "accessKey", accessKey },
                { "requestId", requestId },
                { "amount", amount },
                { "orderId", orderid },
                { "orderInfo", orderInfo },
                { "returnUrl", returnUrl },
                { "notifyUrl", notifyurl },
                { "extraData", extraData },
                { "requestType", "captureMoMoWallet" },
                { "signature", signature }

            };

                string responseFromMomo = PaymentRequest.sendPaymentRequest(endpoint, message.ToString());

                JObject jmessage = JObject.Parse(responseFromMomo);
                lstCart.Clear();
                Session["count"] = 0;
                return Redirect(jmessage.GetValue("payUrl").ToString());
            } 
        }

        #endregion

        #region PaymentCOD
        [HttpGet]
        public ActionResult PaymentCOD()
        {
            return View();
        }
        [HttpPost]
        public ActionResult PaymentCOD(string Name, string Phone, string Address)
        {
            int tong = 0;
            if (Session["idUser"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                var lstCart = (List<Cart>)Session["cart"];
                Order objOrder = new Order();
                objOrder.Name = Name;
                objOrder.Phone = Phone;
                objOrder.Adress = Address;
                objOrder.UserId = int.Parse(Session["idUser"].ToString());
                objOrder.CreateOnUtc = DateTime.Now;
                objOrder.Status = 0;
                db.Order.Add(objOrder);
                db.SaveChanges();
                int intOrderId = objOrder.Id;
                List<OrderDetail> lstOrderDetail = new List<OrderDetail>();
                foreach (var item in lstCart)
                {
                    OrderDetail objOrderDetail = new OrderDetail();
                    objOrderDetail.Quantity = item.Quantity;
                    objOrderDetail.ProductId = item.Product.Id;
                    objOrderDetail.ProductName = item.Product.Name;
                    objOrderDetail.Price = item.Product.Price;
                    int gia = (int)objOrderDetail.Price;
                    int soluong = (int)objOrderDetail.Quantity;
                    int tien = gia * soluong;
                    tong = tong + tien;
                    objOrderDetail.OrderId = intOrderId;
                    lstOrderDetail.Add(objOrderDetail);
                }
                db.OrderDetail.AddRange(lstOrderDetail);
                db.SaveChanges();
                lstCart.Clear();
                Session["count"] = 0;
            }
            return RedirectToAction("Success");
        }
        #endregion

        public ActionResult Success()
        {
            return View();
        }
    }
}

OnlineShop/Views/Shared/_Layout.cshtml
@*<!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - My ASP.NET Application</title>
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
    </html>*@

<style>
    .th {
        width: 250px !important;
    }
</style>
<!DOCTYPE HTML>
<head>
    <title>Điện máy Trường Hoa</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link href="~/Content/css/style.css" rel="stylesheet" type="text/css" media="all" />
    <link href="~/Content/css/slider.css" rel="stylesheet" type="text/css" media="all" />
    
    <script type="text/javascript" src="js/jquery-1.7.2.min.js"></script>
    <script type="text/javascript" src="js/move-top.js"></script>
    <script type="text/javascript" src="js/easing.js"></script>
    <script type="text/javascript" src="js/startstop-slider.js"></script>

    <style>
        .dropbtn {
            background-color: white;
            color: black;
            padding: 10px 0 10px 0;
            font-size: 16px;
            border: none;
            cursor: pointer;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #f9f9f9;
            min-width: 120px;
            box-shadow: 0px 8px 16px 0px rgba(0,0,0,0.2);
            z-index: 1;
        }

            .dropdown-content a {
                float: none;
                color: black;
                height: 25px;
                padding:5px 12px 0 12px;
                text-decoration: none;
                display: block;
                text-align: left;
            }

                .dropdown-content a:hover {
                    background-color: #f1f1f1
                }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        .dropdown:hover .dropbtn {
            background-color: gray;
        }

        .call {
            padding: 10px 0 10px 0;
        }

        .cart {
            padding: unset;
            margin-top: 40px;
        }
    </style>
</head>
<body>
    <div class="wrap">
        <div class="header">
            <div class="headertop_desc">
                <div class="call">
                    <p><span>Cần hỗ trợ?</span> gọi chúng tôi <span class="number">  038 203 9666</span></p>
                </div>
                <div class="account_desc">
                    <ul>
                        @{
                            if (Session["idUser"] != null)
                            {
                                if (Session["Admin"] != null)
                                {
                                    <li>Chào mừng @Session["Fullname"]</li>


                                    <li><a href="~/Admin/HomeAdmin/Index">Trang quản trị</a></li>


                                    <li><a href="~/Home/Logout" class="btn btn-warning">Đăng xuất</a></li>
                                }
                                else
                                {
                                    <li class="dropdown">
                                        <button style="width:120px" class="dropbtn">Tài khoản</button>
                                        <div class="dropdown-content">
                                            <hr />
                                            <a href="~/Home/Infor/@Session["idUser"]">Thông tin</a>
                                            <hr />
                                            <a href="~/Home/ChangePassword/@Session["idUser"]">Đổi mật khẩu</a>
                                            <hr />
                                            <a href="~/Home/Logout" >Đăng xuất</a>
                                        </div>
                                    </li>
                                    <li style="padding:0 0 0 10px">Welcome @Session["Fullname"]</li>
                                }
                            }
                            else
                            {
                                <li><a href="~/Home/Register">Đăng kí</a></li>
                                <li><a href="~/Home/Login">Đăng nhập</a></li>
                            }
                        }
                    </ul>
                </div>
                <div class="clear"></div>
            </div>
            <div class="header_top">
                <div class="logo">
                    <a href="~/Home/Index"><img src="~/Content/images/truonghoa.png" alt="" /></a>
                </div>
                <div class="cart">
                    <p class="th">
                        Điện máy Trường Hoa! <a href="@Url.Action("Index", "Cart" )" ><img style="width:8%" src="~/Content/images/cart.jpg" />:  </a>
                            @Session["count"] sản phẩm
                            
                        
                    </p>
                </div>
                <script type="text/javascript">
                    function DropDown(el) {
                        this.dd = el;
                        this.initEvents();
                    }
                    DropDown.prototype = {
                        initEvents: function () {
                            var obj = this;

                            obj.dd.on('click', function (event) {
                                $(this).toggleClass('active');
                                event.stopPropagation();
                            });
                        }
                    }

                    $(function () {

                        var dd = new DropDown($('#dd'));

                        $(document).click(function () {
                            // all dropdowns
                            $('.wrapper-dropdown-2').removeClass('active');
                        });

                    });

                </script>
                <div class="clear"></div>
            </div>
            
            
        </div>
        @RenderBody()
        <div class="main">
            
        </div>
    </div>
    <div class="footer">
        <div class="wrap">
            <div class="section group">
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Thông tin</h4>
                    <ul>
                        <li><a href="~/About/Index">Trường Hoa</a></li>
                        <li><a href="~/Contact/Index">Chăm sóc khách hàng</a></li>

                        <li><a href="~/Contact/Index">Liên hệ</a></li>
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Tại sao nên mua?</h4>
                    <ul>
                        <li><a href="~/About/Index">Thông tin về chúng tôi</a></li>
                        <li><a href="~/Contact/Index">Dịch vụ chăm sóc khách hàng</a></li>
           
                        <li><a href="~/Contact/Index">Bản đồ</a></li>
                        
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Tài khoản</h4>
                    <ul>
                        <li><a href="~/Home/Login">Đăng nhập</a></li>
                        <li><a href="~/Cart/Index">Giỏ hàng</a></li>
                        <li><a href="~/Contact/Index">Trợ giúp</a></li>
                    </ul>
                </div>
                <div class="col_1_of_4 span_1_of_4">
                    <h4>Liên hệ</h4>
                    <ul>
                        <li><span>0204 388 015</span></li>
                        <li><span>038 203 9666</span></li>
                        
                    </ul>
                    <div class="social-icons">
                        <h4>Theo dõi</h4>
                        <ul>
                            <li><a href="https://www.facebook.com/profile.php?id=100083009238439" target="_blank"><img src="~/Content/images/facebook.png" alt="" /></a></li>
                            
                            
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="copy_right">
            <p> Cửa hàng điện máy Trường Hoa</p>
        </div>
    </div>
    
</body>

OnlineShop/Views/Shared/_Slide.cshtml
<div class="header_slide">
    <div class="header_bottom_left">
        <div class="categories">
            <ul>
                <h3>Categories</h3>
                <li><a href="#">Mobile Phones</a></li>
                <li><a href="#">Desktop</a></li>
                <li><a href="#">Laptop</a></li>
                <li><a href="#">Accessories</a></li>
                <li><a href="#">Software</a></li>
                <li><a href="#">Sports &amp; Fitness</a></li>
                <li><a href="#">Footwear</a></li>
                <li><a href="#">Jewellery</a></li>
                <li><a href="#">Clothing</a></li>
                <li><a href="#">Home Decor &amp; Kitchen</a></li>
                <li><a href="#">Beauty &amp; Healthcare</a></li>
                <li><a href="#">Toys, Kids &amp; Babies</a></li>
            </ul>
        </div>
    </div>
    <div class="header_bottom_right">
        <div class="slider">
            <div id="slider">
                <div id="mover">
                    <div id="slide-1" class="slide">
                        <div class="slider-img">
                            <a href="preview.html"><img src="~/Content/images/slide-1-image.png" alt="learn more" /></a>
                        </div>
                        <div class="slider-text">
                            <h1>Clearance<br><span>SALE</span></h1>
                            <h2>UPTo 20% OFF</h2>
                            <div class="features_list">
                                <h4>Get to Know More About Our Memorable Services Lorem Ipsum is simply dummy text</h4>
                            </div>
                            <a href="preview.html" class="button">Shop Now</a>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="slide">
                        <div class="slider-text">
                            <h1>Clearance<br><span>SALE</span></h1>
                            <h2>UPTo 40% OFF</h2>
                            <div class="features_list">
                                <h4>Get to Know More About Our Memorable Services</h4>
                            </div>
                            <a href="preview.html" class="button">Shop Now</a>
                        </div>
                        <div class="slider-img">
                            <a href="preview.html"><img src="~/Content/images/slide-3-image.jpg" alt="learn more" /></a>
                        </div>
                        <div class="clear"></div>
                    </div>
                    <div class="slide">
                        <div class="slider-img">
                            <a href="preview.html"><img src="~/Content/images/slide-2-image.jpg" alt="learn more" /></a>
                        </div>
                        <div class="slider-text">
                            <h1>Clearance<br><span>SALE</span></h1>
                            <h2>UPTo 10% OFF</h2>
                            <div class="features_list">
                                <h4>Get to Know More About Our Memorable Services Lorem Ipsum is simply dummy text</h4>
                            </div>
                            <a href="preview.html" class="button">Shop Now</a>
                        </div>
                        <div class="clear"></div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="clear"></div>
</div>