OnlineShop/Areas/Admin/Controllers/OrderAdminController.cs
using OnlineShop.Context;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace OnlineShop.Areas.Admin.Controllers
{
    public class OrderAdminController : Controller
    {
        // GET: Admin/OrderAdmin
        ShopEntities1 db = new ShopEntities1();

        #region Get
        public ActionResult Index()
        {
            if (Session["Admin"] != null)
            {
                var cus = db.Order.ToList();
                Order_OrderDetail obj = new Order_OrderDetail();
                obj.lstOrder = cus;
                return View(obj);
            }
            else
            {
                return Redirect("https://localhost:44353/Home/Login");
            }
            
        }
        #endregion

        #region Delete
        [HttpGet]
        public ActionResult Delete(int Id)
        {
            var cus = db.Order.Where(n => n.Id == Id).FirstOrDefault();
            return View(cus);
        }
        [HttpPost]
        public ActionResult Delete(Order order)
        {
            var cus = db.Order.Where(n => n.Id == order.Id).FirstOrDefault();
            db.Order.Remove(cus);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        #endregion

        #region Detail
        public ActionResult Details(Order order)
        {
            var objOrder = db.Order.Where(n => n.Id == order.Id).FirstOrDefault();
            var objOrderDetail = db.OrderDetail.Where(n => n.OrderId == order.Id).FirstOrDefault();
            var lstOrder = db.Order.ToList();
            var lstOrderDetail = db.OrderDetail.Where(n=>n.OrderId==order.Id).ToList();
            var lstproduct = db.Product.Where(n => n.Id == objOrderDetail.ProductId).ToList();
            Order_OrderDetail obj = new Order_OrderDetail();
            obj.objOrderDetail = objOrderDetail;
            obj.objOrder = objOrder;
            obj.lstOrder = lstOrder;
            obj.lstProduct = lstproduct;
            obj.lstOrderDetail = lstOrderDetail;
            return View(obj);
        }
        #endregion

        #region Export

        [HttpPost]
        public ActionResult Export()
        {
            var gv = new GridView();
            gv.DataSource = this.db.OrderDetail.Select(n => new
            {
                NameCus = n.Order.Name,
                Phone = "+"+ n.Order.Phone,
                Address = n.Order.Adress,
                Time = n.Order.CreateOnUtc,
                NameProduct = n.ProductName,
                Quantity = n.Quantity,
                Price = n.Price,
                Money = n.Quantity * n.Price
            }).OrderByDescending(p => p.Time).ToList();
            gv.DataBind();
            Response.Clear();
            Response.Buffer = true;
            //Response.AddHeader("content-disposition",
            // "attachment;filename=GridViewExport.xls");
            Response.Charset = "utf-8";
            Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
            Response.AddHeader("content-disposition", "attachment;filename=Danh Sách Đơn.xls");
            //Mã hóa chữa sang UTF8
            Response.ContentEncoding = System.Text.Encoding.UTF8;
            Response.BinaryWrite(System.Text.Encoding.UTF8.GetPreamble());

            StringWriter sw = new StringWriter();
            HtmlTextWriter hw = new HtmlTextWriter(sw);

            for (int i = 0; i < gv.Rows.Count; i++)
            {
                //Apply text style to each Row
                gv.Rows[i].Attributes.Add("class", "textmode");
            }
            //Add màu nền cho header của file excel
            gv.HeaderRow.BackColor = System.Drawing.Color.DarkBlue;
            //Màu chữ cho header của file excel
            gv.HeaderStyle.ForeColor = System.Drawing.Color.White;

            gv.HeaderRow.Cells[0].Text = "Tên khách hàng";
            gv.HeaderRow.Cells[1].Text = "Số điện thoại";
            gv.HeaderRow.Cells[2].Text = "Địa chỉ";
            gv.HeaderRow.Cells[3].Text = "Thời gian đặt hàng";
            gv.HeaderRow.Cells[4].Text = "Tên sản phẩm";
            gv.HeaderRow.Cells[5].Text = "Số lượng";
            gv.HeaderRow.Cells[6].Text = "Giá";
            gv.HeaderRow.Cells[7].Text = "Thành tiền";
            gv.RenderControl(hw);

            Response.Output.Write(sw.ToString());
            Response.Flush();
            Response.End();
            var model = db.OrderDetail.OrderByDescending(p => p.Order.CreateOnUtc)
                .ToList();
            return View("View", model);
        }
        #endregion
    }
}

OnlineShop/Areas/Admin/Views/OrderAdmin/Delete.cshtml
@model OnlineShop.Context.Order

@{
    ViewBag.Title = "Delete";
}
<h2>Bạn muốn xóa đơn hàng này?</h2>
<div>
    <div id="dataTables_wrapper" class="dataTables_wrapper">
        <table class="table">
            <thead>
                <tr>

                    <th>
                        <p>Tên</p>
                    </th>
                    <th>
                        <p>Thời gian đặt</p>
                    </th>
                    <th>
                        <p>SDT</p>
                    </th>
                    <th>
                        <p>Địa chỉ</p>
                    </th>


                </tr>
            </thead>
            <tbody>
                <tr>

                    <td>
                        @Model.Name
                    </td>
                    <td>
                        @Model.CreateOnUtc
                    </td>
                    <td>
                        @Model.Phone
                    </td>
                    <td>
                        @Model.Adress
                    </td>
                </tr>
            </tbody>
        </table>
    </div>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="modal-footer">
            <input type="submit" value="Xóa" class="btn btn-danger" />
            @Html.ActionLink("Trở lại danh sách", "Index")
        </div>
    }
</div>

OnlineShop/Areas/Admin/Views/OrderAdmin/Details.cshtml
@model OnlineShop.Areas.Order_OrderDetail

@{
    ViewBag.Title = "Details";
}

<h2>Đơn hàng của @Model.objOrder.Name đặt lúc @Model.objOrder.CreateOnUtc</h2>

<br />
@{ int all = 0;
    }

<table class="table">
    <tr>
        
        <th>
            <p>Tên sản phẩm</p>
        </th>
        <th>
            <p>Số lượng</p>
        </th>
        <th>
            <p>Giá sản phẩm</p>
        </th>
        <th>
            <p>Thành tiền</p>
        </th>
    </tr>

@foreach (var item in Model.lstOrderDetail) {
    <tr>
        
        <td>
            @item.ProductName
        </td>
        <td>
            @item.Quantity
        </td>
        <td>
            @{ 
                string tien = "";
                int gia = (int)item.Price;
                tien = gia.ToString("#,##0");
            }
            @tien
        </td>
        <td>
            @{ 
                int tong = (int)(item.Price * item.Quantity);
                string tt = "";
                tt = tong.ToString("#,##0");
                all = all + tong;
            }
            @tt
        </td>
        
    </tr>

}
    <tr>
        <td></td>
        <td></td>
        <td width="200">
            Thành tiền: 
        </td>
        <td width="200" style="color:orangered">
            @{ 
                string abc = all.ToString("#,##0");
            }
            @abc
        </td>
    </tr>
</table>

OnlineShop/Areas/Admin/Views/OrderAdmin/Index.cshtml
@model OnlineShop.Areas.Order_OrderDetail

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Danh sách sản phẩm </h3>
            </div>
            <div class="card-body">
                <div class="row">
                    <div class="table-control col-sm-12 col-md-6">
                        
                    </div>
                    <div class="table-control col-sm-12 col-md-6 text-right">
                        
                        <a class="btn exportByByte">
                            @using (Html.BeginForm("Export", "OrderAdmin", FormMethod.Post))
                            {
                                <input type="submit" value="Xuất hóa đơn" />
                            }
                        </a>
                    </div>
                </div>

                <div id="dataTables_wrapper" class="dataTables_wrapper">
                    <table class="table">
                        <thead>
                            <tr>

                                <th>
                                    <p>Tên</p>
                                </th>
                                <th>
                                    <p>Thời gian đặt hàng</p>
                                </th>
                                <th>
                                    <p>SDT</p>
                                </th>
                                <th>
                                    <p>Địa chỉ</p>
                                </th>
                                <th>
                                    <p>Trạng thái</p>
                                </th>
                                <th>
                                    Thao tác
                                </th>

                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.lstOrder)
                            {
                            <tr>

                                <td>
                                    @item.Name
                                </td>
                                <td>
                                    @item.CreateOnUtc
                                </td>
                                <td>
                                    @item.Phone
                                </td>
                                <td>
                                    @item.Adress
                                </td>
                                <td>
                                    @{
                                        var stt = "";
                                        if (item.Status == 1)
                                        {
                                            stt = "Đã thanh toán";
                                        }
                                        else
                                        {
                                            stt = "Chưa thanh toán";
                                        }
                                    }
                                    @stt
                                </td>

                                <td>
                                    <a title="Xem chi tiết" class="btn btn-sm btn-outline-secondary btn-hover-success quickUpdate" href="~/Admin/OrderAdmin/Details/@item.Id">
                                        <i class="fas fa-fw fa-info"></i>
                                    </a>
                                    <a title="Xóa" class="btn btn-sm btn-outline-secondary btn-hover-danger quickDelete" href="~/Admin/OrderAdmin/Delete/@item.Id">
                                        <i class="fas fa-fw fa-trash-alt"></i>
                                    </a>
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>